//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scullion.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderProduct = new HashSet<OrderProduct>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductArticle { get; set; }
        public string ProductUnit { get; set; }
        public decimal ProductCost { get; set; }
        public double ProductMaxDiscount { get; set; }
        public int ProductManufactureID { get; set; }
        public int ProductSupplierID { get; set; }
        public int ProductTypeID { get; set; }
        public double ProductCurrentDiscount { get; set; }
        public int ProductCountInStock { get; set; }
        public string ProductDescription { get; set; }
        public string ProductImage { get; set; }
    
        public virtual Manufacture Manufacture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProduct { get; set; }
        public virtual ProductType ProductType { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
